# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        nursing care AI: 5
        consciousness AI: 5
        Consciousness reinforcement learning: 5
        pose skeleton: 5
        human pose: 5
        re-id: 5
        Personal Identification: 5
        pose estimation: 3
        

# 通知の閾値
score_threshold: 0
