# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        occlusion: 5
        openpose: 5
        pose tracking: 5
        skelton pose: 5
        person re-id one-shot learning: 5
        person re-id: 3
        re-id: 2

# 通知の閾値
score_threshold: 0
