# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        nursing care AI: 5
        openpose: 5
        person re-id one-shot learning: 4
        2D Skeleton Pose: 3
        person re-id: 3
        pose tracking: 3
        
        

# 通知の閾値
score_threshold: 0
